### ISSUE TITLE
Exercise 1: Redirection paths not reflected in all URL's

### ISSUE THREAD

**Issue by rduerr** [fcrepo4-labs/fcrepo-api-x-demo#35]
In order to get the localhost api-x redirects working on my Mac, I had to replace a line in the api-x section of the docker-compose.yam file.  The original version is:

```
  apix:
    image: fcrepoapix/apix-core:latest
    container_name: apix
    env_file: apix.env
    ports:
      - "80:80"
      - "8081:8081"
    depends_on:
      - fcrepo

```
My version is

 ```
 apix:
    image: fcrepoapix/apix-core:latest
    container_name: apix
    env_file: apix.env
    ports:
      - "8000:80"
      - "8081:8081"
    depends_on:
      - fcrepo
```

This works fine except that all of the api-x urls now have to be of the form http://localhost:8000/fcrepo/rest...

This generally works ok, until you start adding objects to the repository. While most of the links in the new objects are ok (i.e., have localhost:8000 in them); not all of them do.  In particular, the discovery links don't seem to.

Here is an example from the first exercise...

```
curl -I http://localhost:8000/fcrepo/rest/MyImages/ImageOday
HTTP/1.1 200 OK
Content-Type: image/png
Accept: */*
Accept-Ranges: bytes
Allow: DELETE,HEAD,GET,PUT,OPTIONS
Apix-Modality: intercept; outgoing
breadcrumbId: ID-f5ded377df95-43061-1484958008087-1-206
Content-Disposition: attachment; filename="Image.png"; creation-date="Sat, 21 Jan 2017 00:44:27 GMT"; modification-date="Sat, 21 Jan 2017 00:44:27 GMT"; size=150185
ETag: "2ebaa504fd9eddb090d1cc63307954065ee50d7c"
Last-Modified: Sat, 21 Jan 2017 00:44:27 GMT
Link: <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type"
Link: <http://localhost/discovery/MyImages/ImageOday>; rel="service"
Link: <http://localhost:8000/fcrepo/rest/MyImages/ImageOday/fcr:metadata>; rel="describedby"
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Content-Length: 0
Server: Jetty(9.2.19.v20160908)

Ruths-iMac:fcrepo-api-x-demo ruthduerr$ curl http://localhost/discovery/MyImages/ImageOday
curl: (52) Empty reply from server
Ruths-iMac:fcrepo-api-x-demo ruthduerr$ curl http://localhost:8000/discovery/MyImages/ImageOday
<>      a       <http://fedora.info/definitions/v4/service#ServiceDocument> ;
        <http://fedora.info/definitions/v4/service#isServiceDocumentFor>
                <http://localhost/fcrepo/rest/MyImages/ImageOday> ;
        <http://www.openarchives.org/ore/terms/describes>
                <#services> .
Ruths-iMac:fcrepo-api-x-demo ruthduerr$ 

```
As you can see the discovery service link does not have the :8000 while the very next line (the metadata link) does.  As you might expect the discovery link does not work as written.... a :8000 must be manually added in order for it to work.  

This indicates that the code creating the discovery path is not paying attention to the contents of the YAML file.  All code needs to pay attention to the contents of these sorts of configuration files.

**Comment by emetsger** [comment]
Hi @rduerr,

Presuming your apix container still reads:
```
apix:
   image: fcrepoapix/apix-core:latest
   container_name: apix
   env_file: apix.env
   ports:
     - "8000:80"
     - "8081:8081"
   depends_on:
     - fcrepo
```

It looks like we missed a trick with the setup.  You'll need to edit the `apix.env` file (steps below) to reflect the updated port.

1.  Destroy your containers (`docker-compose down`)
2. Edit `apix.env` (in the same directory as `docker-compose.yaml`) and have the entirety of the file read:
```
APIX_PORT=8000
```
3.  Start docker (`docker-compose up -d`)

I think at that point you should be able to continue with the exercises, with port `8000` reflected in the service URLs
